[pytest]
asyncio_mode = auto
filterwarnings =
    ignore::DeprecationWarning
env =
    DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/hh_parser_test
    DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/hh_parser_test
    DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/hh_parser_test
